### ISSUE TITLE
`pip install -r requirements.txt` got error

### ISSUE THREAD

**Issue by liqwang** [deligentfool/mfrl_pytorch#1]
My environment is linux-x64 with Python 3.9.18

After I execute `pip install -r requirements.txt`, I got the following error caused by dependency conflict: 
```
The conflict is caused by:
    The user requested numpy==1.21.2
    array2gif 1.0.4 depends on numpy
    contourpy 1.0.6 depends on numpy>=1.16
    gym 0.21.0 depends on numpy>=1.18.0
    imageio 2.13.3 depends on numpy
    magent 0.1.14 depends on numpy>=1.18.0
    matplotlib 3.6.2 depends on numpy>=1.19
    mkl-fft 1.3.1 depends on numpy<1.23.0 and >=1.22.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Besides the dependency conflict problems, there are other problems in `requirements.txt`:
- `prl==0.1.0` isn't a valid version:  https://pypi.org/project/prl/#history
  https://github.com/deligentfool/mfrl_pytorch/blob/cc67da79bac2717f3b275305c14e69967b72becb/requirements.txt#L45
- `pip` isn't neccessary
  https://github.com/deligentfool/mfrl_pytorch/blob/cc67da79bac2717f3b275305c14e69967b72becb/requirements.txt#L44
- `torchaudio==0.7.0a0+a853dff` isn't consistent with the [official install command](https://pytorch.org/get-started/previous-versions/#v171), the correct version should be `torchaudio==0.7.2`
  https://github.com/deligentfool/mfrl_pytorch/blob/cc67da79bac2717f3b275305c14e69967b72becb/requirements.txt#L73

**Comment by liqwang** [comment]
I try to fix the above dependency conflict error by changing numpy version to 1.22.3
```diff
- numpy==1.21.2
+ numpy==1.22.3
```
Then I got another dependency conflict error:
```
The conflict is caused by:
    The user requested numpy==1.22.3
    array2gif 1.0.4 depends on numpy
    contourpy 1.0.6 depends on numpy>=1.16
    gym 0.21.0 depends on numpy>=1.18.0
    imageio 2.13.3 depends on numpy
    magent 0.1.14 depends on numpy>=1.18.0
    matplotlib 3.6.2 depends on numpy>=1.19
    mkl-fft 1.3.1 depends on numpy<1.23.0 and >=1.22.3
    mkl-random 1.2.2 depends on numpy<1.25.0 and >=1.24.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by deligentfool** [comment]
Thank you very much for raising the issue regarding `requirements.txt`. I have already updated the `requirements.txt` file. Please do not hesitate to contact me if you have any further questions.

**Comment by liqwang** [comment]
Thank you very much!
